/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.ListModel;

/**
 *
 * @author Chochu
 */
public class ClientGUI extends javax.swing.JFrame {

	/**
	 * Creates new form ClientGUI
	 */
	public ClientGUI(ClientNet x) {
		clientnet = x;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		Tab = new javax.swing.JTabbedPane();
		Main_ScrollPane = new javax.swing.JScrollPane();
		Room_Jlist = new javax.swing.JList<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		Room_Jlist.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Room 1", "Room 2", "Room 3", "Room 4" };
			public int getSize() { return strings.length; }
			public String getElementAt(int i) { return strings[i]; }
		});
		Room_Jlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
		Room_Jlist.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				Room_JlistMouseClicked(evt);
			}
		});
		Main_ScrollPane.setViewportView(Room_Jlist);

		Tab.addTab("Main", Main_ScrollPane);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(Tab)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(Tab, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void Room_JlistMouseClicked(java.awt.event.MouseEvent evt) {                                        
		// Open a new tab
		if(evt.getClickCount() == 2){
			int index = Room_Jlist.locationToIndex(evt.getPoint());
			ListModel dlm = Room_Jlist.getModel();
			Object item = dlm.getElementAt(index);;
			Room_Jlist.ensureIndexIsVisible(index);
						
			
			Tab.addTab(""+item, new ChatTabPane(clientnet,""+item));
			
		}
	}                                       
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ClientGUI client = new ClientGUI(new ClientNet());
				client.setVisible(true);
				client.setSize(800,600);
			}
		});
	}

	// Variables declaration - do not modify                     
	private javax.swing.JScrollPane Main_ScrollPane;
	private javax.swing.JList<String> Room_Jlist;
	private javax.swing.JTabbedPane Tab;
	private ClientNet clientnet;
	// End of variables declaration                   
}
