/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import javax.swing.JOptionPane;

/**
 *
 * @author Chochu
 */
public class LoginPane extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanelLogin
     */
    public LoginPane(ClientNet client) {
    	clientnet = client;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Password_Label = new javax.swing.JLabel();
        Sendup_Button = new javax.swing.JButton();
        Login_Button = new javax.swing.JButton();
        Username_Label = new javax.swing.JLabel();
        Username_Textfield = new javax.swing.JTextField();
        Password_textfield = new javax.swing.JPasswordField();

        Password_Label.setText("Password");

        Sendup_Button.setText("Sign Up");
        Sendup_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					Sendup_ButtonActionPerformed(evt);
				} catch (NoSuchAlgorithmException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (UnsupportedEncodingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					Login_ButtonActionPerformed(evt);
				} catch (NoSuchAlgorithmException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (UnsupportedEncodingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        Username_Label.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username_Label)
                    .addComponent(Password_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Login_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sendup_Button))
                    .addComponent(Username_Textfield)
                    .addComponent(Password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Username_Label)
                            .addComponent(Username_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Password_Label))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Button)
                    .addComponent(Sendup_Button))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
    }// </editor-fold>                        

    private void Sendup_ButtonActionPerformed(java.awt.event.ActionEvent evt) throws NoSuchAlgorithmException, UnsupportedEncodingException {                                              
    	MessageDigest digest = MessageDigest.getInstance("SHA-256");
    	StringBuilder sb = new StringBuilder(64); 
    	sb.append("a83920d1348eee579e4d5e2037b93657".toCharArray()); //add salt to stringbuilder
    	sb.append(Password_textfield.getPassword()); //add password to stringbuilder
    	byte[] hash = digest.digest(new String(sb).getBytes("UTF-8"));
    	if(true){ //send to server
    		JOptionPane.showMessageDialog(null, "Account created sucessfully", "Success", JOptionPane.INFORMATION_MESSAGE);
    	}
    	else
    		JOptionPane.showMessageDialog(null, "Fail to create account", "Error", JOptionPane.INFORMATION_MESSAGE);
    }                                             

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) throws NoSuchAlgorithmException, UnsupportedEncodingException {
    	MessageDigest digest = MessageDigest.getInstance("SHA-256");
    	StringBuilder sb = new StringBuilder(64); 
    	sb.append("a83920d1348eee579e4d5e2037b93657".toCharArray()); //add salt to stringbuilder
    	sb.append(Password_textfield.getPassword()); //add password to stringbuilder
    	byte[] hash = digest.digest(new String(sb).getBytes("UTF-8"));
    	Username = Username_Textfield.getText();
    	HashPassword = String.format("%064x", new java.math.BigInteger(1,hash));
    	LoginisClick = true;
//    	if(true){ //send to server 
//    		isLogin = true;
//    	}
        //StringBuffer Buff_Password = new StringBuffer(new String(Str_Password)); //Turn password into string buffer
    }                                            

//    boolean getisLogin(){
//    	return isLogin;
//    }

    // Variables declaration - do not modify
    protected String Username;
    protected String HashPassword;
    private ClientNet clientnet;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JPasswordField Password_textfield;
    private javax.swing.JButton Sendup_Button;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JTextField Username_Textfield;
    private javax.swing.JPanel jPanel1;
    protected boolean LoginisClick = false;
    // End of variables declaration                   
}
